import { AdminApiError } from "./api";

export const ADMIN_COMMAND_ERROR_CODES = [
  "ADMIN_AUTH_REQUIRED", "ADMIN_REAUTH_REQUIRED", "AGENT_NOT_FOUND", "AGENT_SLUG_ALREADY_EXISTS",
  "CAPACITY_BELOW_OCCUPANCY", "CITY_HAS_OCCURRENCES", "CITY_NOT_FOUND",
  "CITY_SLUG_CONFLICT", "CITY_SLUG_UNKNOWN", "CONFIRMATION_REQUIRED",
  "CONTRACTOR_STATUS_REVIEW", "EMAIL_ATTENTION_ACKNOWLEDGEMENT_REASON_REQUIRED",
  "EMAIL_ATTENTION_NOT_ACTIONABLE", "EMAIL_OUTBOX_NOT_FOUND", "IDEMPOTENCY_CONFLICT", "IMMUTABLE_FIELD",
  "IDEMPOTENCY_CONTRACT_SUPERSEDED", "IDEMPOTENCY_KEY_INVALID", "IDEMPOTENCY_KEY_REQUIRED", "INVALID_CREDENTIALS", "INVALID_JSON",
  "OCCURRENCE_NOT_ENDED", "OCCURRENCE_NOT_FOUND", "OCCURRENCE_REVISION_CONFLICT",
  "OCCURRENCE_SALES_MUST_BE_CLOSED", "OCCURRENCE_STATE_TRANSITION_FORBIDDEN",
  "OCCURRENCE_TERMINAL", "OPERATIONAL_INCIDENT_NOT_OPEN", "ORDER_NOT_FOUND",
  "ORIGIN_FORBIDDEN", "PAYMENT_ALREADY_SUCCEEDED", "PAYMENT_NOT_REFUNDABLE",
  "PROMO_CODE_ALREADY_EXISTS", "PROMO_NOT_FOUND", "PROVIDER_RECONCILIATION_UNAVAILABLE", "RATE_LIMITED", "REFUND_AMOUNT_EXCEEDS_AVAILABLE", "DRIFT_REVIEW_NOT_OPEN", "RESOLUTION_NOTE_REQUIRED",
  "RESERVATION_NOT_ABANDONABLE", "SETTLEMENT_BUSY", "SETTLEMENT_EXCEEDS_AVAILABLE",
  "SETTLEMENT_NOT_FOUND", "SETTLEMENT_RECOVERY_AMOUNT_INVALID",
  "SETTLEMENT_RECOVERY_EXCEEDS_REMAINING", "SETTLEMENT_RECOVERY_NOT_PAID",
  "SETTLEMENT_TRANSITION_FORBIDDEN", "VALIDATION_ERROR", "VENUE_ANNOUNCEMENT_TOO_LATE",
] as const;

export type AdminCommandErrorCode = (typeof ADMIN_COMMAND_ERROR_CODES)[number];
export type IdempotencyDisposition = "RETAIN_KEY" | "MAY_MINT_NEW_KEY";
export type RefreshDisposition = "REFRESH_AUTHORITATIVE_STATE" | "NO_REFRESH_NEEDED";

/**
 * Every code currently returned by an admin command route is deliberately
 * classified. New backend codes must be added here rather than accidentally
 * inheriting an optimistic "any 4xx is safe" policy.
 *
 * Idempotency and freshness are separate policies: a command can be safely
 * rejected yet still expose that another operator changed the record.
 */
export const IDEMPOTENCY_DISPOSITION: Record<AdminCommandErrorCode, IdempotencyDisposition> = {
  ADMIN_AUTH_REQUIRED: "MAY_MINT_NEW_KEY", ADMIN_REAUTH_REQUIRED: "MAY_MINT_NEW_KEY", AGENT_NOT_FOUND: "MAY_MINT_NEW_KEY", AGENT_SLUG_ALREADY_EXISTS: "MAY_MINT_NEW_KEY",
  CAPACITY_BELOW_OCCUPANCY: "MAY_MINT_NEW_KEY", CITY_HAS_OCCURRENCES: "MAY_MINT_NEW_KEY", CITY_NOT_FOUND: "MAY_MINT_NEW_KEY",
  CITY_SLUG_CONFLICT: "MAY_MINT_NEW_KEY", CITY_SLUG_UNKNOWN: "MAY_MINT_NEW_KEY", CONFIRMATION_REQUIRED: "MAY_MINT_NEW_KEY",
  CONTRACTOR_STATUS_REVIEW: "MAY_MINT_NEW_KEY", EMAIL_ATTENTION_ACKNOWLEDGEMENT_REASON_REQUIRED: "MAY_MINT_NEW_KEY",
  EMAIL_ATTENTION_NOT_ACTIONABLE: "MAY_MINT_NEW_KEY", EMAIL_OUTBOX_NOT_FOUND: "MAY_MINT_NEW_KEY", IDEMPOTENCY_CONFLICT: "RETAIN_KEY", IMMUTABLE_FIELD: "MAY_MINT_NEW_KEY",
  IDEMPOTENCY_CONTRACT_SUPERSEDED: "RETAIN_KEY", IDEMPOTENCY_KEY_INVALID: "MAY_MINT_NEW_KEY", IDEMPOTENCY_KEY_REQUIRED: "MAY_MINT_NEW_KEY", INVALID_CREDENTIALS: "MAY_MINT_NEW_KEY", INVALID_JSON: "MAY_MINT_NEW_KEY",
  OCCURRENCE_NOT_ENDED: "MAY_MINT_NEW_KEY", OCCURRENCE_NOT_FOUND: "MAY_MINT_NEW_KEY", OCCURRENCE_REVISION_CONFLICT: "MAY_MINT_NEW_KEY",
  OCCURRENCE_SALES_MUST_BE_CLOSED: "MAY_MINT_NEW_KEY", OCCURRENCE_STATE_TRANSITION_FORBIDDEN: "MAY_MINT_NEW_KEY",
  OCCURRENCE_TERMINAL: "MAY_MINT_NEW_KEY", OPERATIONAL_INCIDENT_NOT_OPEN: "MAY_MINT_NEW_KEY", ORDER_NOT_FOUND: "MAY_MINT_NEW_KEY",
  ORIGIN_FORBIDDEN: "MAY_MINT_NEW_KEY", PAYMENT_ALREADY_SUCCEEDED: "MAY_MINT_NEW_KEY", PAYMENT_NOT_REFUNDABLE: "MAY_MINT_NEW_KEY",
  PROMO_CODE_ALREADY_EXISTS: "MAY_MINT_NEW_KEY", PROMO_NOT_FOUND: "MAY_MINT_NEW_KEY", PROVIDER_RECONCILIATION_UNAVAILABLE: "RETAIN_KEY", RATE_LIMITED: "MAY_MINT_NEW_KEY", REFUND_AMOUNT_EXCEEDS_AVAILABLE: "MAY_MINT_NEW_KEY", DRIFT_REVIEW_NOT_OPEN: "MAY_MINT_NEW_KEY", RESOLUTION_NOTE_REQUIRED: "MAY_MINT_NEW_KEY",
  RESERVATION_NOT_ABANDONABLE: "MAY_MINT_NEW_KEY", SETTLEMENT_BUSY: "MAY_MINT_NEW_KEY", SETTLEMENT_EXCEEDS_AVAILABLE: "MAY_MINT_NEW_KEY",
  SETTLEMENT_NOT_FOUND: "MAY_MINT_NEW_KEY", SETTLEMENT_RECOVERY_AMOUNT_INVALID: "MAY_MINT_NEW_KEY",
  SETTLEMENT_RECOVERY_EXCEEDS_REMAINING: "MAY_MINT_NEW_KEY", SETTLEMENT_RECOVERY_NOT_PAID: "MAY_MINT_NEW_KEY",
  SETTLEMENT_TRANSITION_FORBIDDEN: "MAY_MINT_NEW_KEY", VALIDATION_ERROR: "MAY_MINT_NEW_KEY", VENUE_ANNOUNCEMENT_TOO_LATE: "MAY_MINT_NEW_KEY",
};

export const REFRESH_DISPOSITION: Record<AdminCommandErrorCode, RefreshDisposition> = Object.fromEntries(
  ADMIN_COMMAND_ERROR_CODES.map((code) => [
    code,
    ["ADMIN_AUTH_REQUIRED", "IDEMPOTENCY_KEY_INVALID", "IDEMPOTENCY_KEY_REQUIRED", "INVALID_CREDENTIALS", "INVALID_JSON", "ORIGIN_FORBIDDEN", "RATE_LIMITED", "RESOLUTION_NOTE_REQUIRED", "VALIDATION_ERROR"].includes(code)
      ? "NO_REFRESH_NEEDED"
      : "REFRESH_AUTHORITATIVE_STATE",
  ]),
) as Record<AdminCommandErrorCode, RefreshDisposition>;

export function safeToMintNewKey(error: AdminApiError): boolean {
  if (error.status === 401 || error.status === 403 || error.status === 429) return true;
  return IDEMPOTENCY_DISPOSITION[error.code as AdminCommandErrorCode] === "MAY_MINT_NEW_KEY";
}

export const shouldRefreshAuthoritativeState = (error: AdminApiError) =>
  error.status === 0 || error.status >= 500 || REFRESH_DISPOSITION[error.code as AdminCommandErrorCode] !== "NO_REFRESH_NEEDED";
